[package]
name = "tsp"
version = "0.1.0"
authors = ["Logan Teder"]
description = "Genetic program to solve the travelling salesperson problem"

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
rand = "0.8.5"

[profile.dev]
opt-level = 2
